name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Dart Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Run linter
        run: flutter analyze

  build:
    name: Build Flutter Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      - name: Get dependencies
        run: flutter pub get

      - name: Build web
        run: flutter build web

  deploy:
    name: Deploy to Nhost
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Nhost
        env:
          NHOST_AUTH_TOKEN: ${{ secrets.NHOST_AUTH_TOKEN }}
        run: |
          curl -X POST https://api.nhost.io/v1/deploy \
            -H "Authorization: Bearer $NHOST_AUTH_TOKEN" \
            -F source=@build/web
